### ISSUE TITLE
External force during goal following

### ISSUE THREAD

**Issue by dorkamotorka** [UbiquityRobotics/move_basic#80]
Currently if the robot is moving towards the goal and is moved or hit by some other dynamic object it does not update it's pose according to the goal and therefore misses it.

PROPOSED SOLUTION: 
Keep track of goal_frame~base_frame transform during movement and update it accordingly if needed.

**Comment by MoffKalast** [comment]
@tp4348 I've just done a round of tests with ezmap and feature-external-force in gazebo and it performs super well, at least as long as the map localization manages to actually find the new position properly. So if it works well in real life tests I'd vote for it to be merged into kinetic-devel as soon as possible since it's really a much needed addition.

**Comment by dorkamotorka** [comment]
Well yeah it's updating in map frame haha. I think I will be able to test it on Sunday if @GreTimotej can't make it earlier.

**Comment by MoffKalast** [comment]
Yep, it's expected, I'm just saying we might need to look at iris_lama next if we're still having problems afterwards.

**Comment by GreTimotej** [comment]
Today I tried the above mentioned issue. I was moving the robot while driving and it went back to its course. I think that is it?

**Comment by MoffKalast** [comment]
That's mostly it, but I think there were some issues with it the first time it was tested? Are those resolved?

**Comment by dorkamotorka** [comment]
Timotej was the one testing it so I guess since the second testing was successful we can close this.

**Comment by dorkamotorka** [comment]
On which branch were you testing @GreTimotej? This one: https://github.com/UbiquityRobotics/move_basic/tree/feature-external-force?
